version: '2.1'

services:
  configServer-service:
    build: configServer/
    mem_limit: 512m
    ports:
      - "8888:8888"

  eureka-service:
    build: eureka-server/
    mem_limit: 512m
    ports:
      - "8761:8761"

  movie-service:
    build: movie-service-parcial/
    mem_limit: 512m
    depends_on:
      mongodb:
        condition: service_healthy

  serie-service:
    build: serie/
    mem_limit: 512m
    depends_on:
      monodb:
        condition: service_healthy

  catalog-service:
    build: catalog-service-parcial/
    mem_limit: 512m
    depends_on:
      monodb:
        condition: service_healthy
        
  gateway-service:
    build: gateway/
    mem_limit: 512m
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:4.4.2
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60